apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-jenkins
  template:
    metadata:
      labels:
        app: nginx-jenkins
    spec:
      containers:
      - name: nginx
        image: my-nginx:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-jenkins-service
spec:
  selector:
    app: nginx-jenkins
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
